contact_links:
  - name: ğŸ’ Idea / Feature request
    url: https://github.com/Building-acoustics-TU-Eindhoven/CHORAS/discussions/new?category=ideas
    about: Suggest an idea / feature for a future version of CHORAS
  - name: ğŸ™‰ Help
    url: https://github.com/Building-acoustics-TU-Eindhoven/CHORAS/
    about: If you need help with CHORAS, either as a developer or as a user, click here.